# Generated by Django 5.0.3 on 2024-03-31 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="lat",
            new_name="addr_lat",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="lng",
            new_name="addr_lng",
        ),
    ]
